### ISSUE TITLE
Ebrary Validation Included False Negatives

### ISSUE THREAD

**Issue by EthanDF** [UNC-Libraries/Ebook-Access-Checker#6]
I'm a noob to github, so please excuse (and advise of) any etiquette failures. I attempted to use this script with the ebrary platform and found that the script was providing false negatives (ie indicating full access when I that was not the case). The text in the original script that triggered the no access seems to be: "if page.include?("Document Unavailable\.")" however, that string, with the "\" did not appear on the page for me. I updated the string (because the code is so clear and clean) to be "Sorry, this ebook is not available at your library" with no slash and that gave me correct results. However, since I know nothing about ruby, I wasn't sure if the slash was used for some other purpose. If you can advise, that would be great. Also, I wanted to make sure I made note so that other users wouldn't get false negatives and assume access. Thanks! 

  elsif package == "ebr"
    sleeptime = 1
    if page.include?("Sorry, this ebook is not available at your library")
      access = "No access"
    elsif page.include?("Date Published")
        access = "Full access"
    else
      access = "Check access manually"
    end

script indicated full access for this page:
![image](https://cloud.githubusercontent.com/assets/3751586/4491101/fd83552e-4a34-11e4-956a-7134022de244.png)

**Comment by kspurgin** [comment]
The main etiquette failure is mine in not seeing that there were issues that needed to be addressed for a ridiculously long period of time, and not responding to this until now. 

Thanks for reporting this. I think it got resolved when we got moved off the old Ebrary platform onto the newer Proquest ebrary platform.
